---

name:
    build-run-watch
version:
    0.1.0.0
synopsis:
    Building, Running & Watching Utilities for Servers and Clients.
# description:
github:
    prikhi/build-run-watch
license:
    BSD-3-Clause
license-file:
    LICENSE
author:
    Pavan Rikhi
maintainer:
    pavan.rikhi@gmail.com
copyright:
    2019 Pavan Rikhi
# category:

extra-source-files:
    - README.md
    - CHANGELOG.md


ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints


library:
    source-dirs:
        src
    dependencies:
        - base >= 4.7 && < 5
        - ansi-terminal >= 0.6 && < 1
        - text >= 1 && < 2
        - typed-process >= 0.1 && < 1
        - unliftio >= 0.2.1 && < 1
        - fsnotify >= 0.1 && < 1
