---

name:
    build-run-watch
version:
    0.1.0.0
synopsis:
    Building, Running & Watching Utilities for Servers and Clients.
description: >
    A package for writing project build tools and management scripts.

    build-run-watch exposes types and functions to facilitate management &
    building of servers and clients. Using the utilities in this package, you
    can easily write a script for making production builds, cleaning build
    artifacts, and easing development. 
    
    Development builds can use the watching utilities to build your server &
    client, start/serve them, and then re-build & re-launch them when their
    source files change.

    Building output is prettily printed with Client/Server/Info/Failure/Success
    tags.

    Currently, only various low-level utilities are exposed for running
    commands, installing dependencies, logging output, and watching
    directories. There are some specialized verisons of these utilities for
    Stack & NPM projects.

    An eventual goal is to present a management function that takes a
    build/watch configuration and generates a CLI application that exposes some
    fixed functionality(production builds, dev/watch mode, cleaning, launching
    REPLs, help text, etc.). Also desired is a TUI mode that shows the logs in
    a Brick UI, allowing you to manually kick off builds or restart the
    watchers.
github:
    prikhi/build-run-watch
license:
    BSD-3-Clause
license-file:
    LICENSE
author:
    Pavan Rikhi
maintainer:
    pavan.rikhi@gmail.com
copyright:
    2019 Pavan Rikhi
category:
    Build, Build Tool, Development

extra-source-files:
    - README.md
    - CHANGELOG.md


ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints


library:
    source-dirs:
        src
    dependencies:
        - base >= 4.7 && < 5
        - ansi-terminal >= 0.6 && < 1
        - fsnotify >= 0.1 && < 1
        - mtl >= 2.1 && < 3
        - text >= 1 && < 2
        - typed-process >= 0.1 && < 1
        - unliftio >= 0.2.1 && < 1
