---

name:
    build-serve
version:
    0.1.0.0
synopsis:
    Building & watching utilities for servers and clients.
# description:
github:
    prikhi/build-serve
license:
    BSD-3-Clause
license-file:
    LICENSE
author:
    Pavan Rikhi
maintainer:
    pavan.rikhi@gmail.com
copyright:
    2019 Pavan Rikhi
# category:

extra-source-files:
    - README.md
    - CHANGELOG.md


ghc-options:
    - -pedantic


library:
    source-dirs:
        src
    dependencies:
        - base >= 4.7 && < 5
        - ansi-terminal >= 0.6 && < 1
        - lifted-async >= 0.8 && < 1
        - monad-control >= 1 && < 2
        - stm >= 2.4 && < 3
        - text >= 1 && < 2
